export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as About } from './about/About'
export { default as Services } from './services/Services'
export { default as Skills } from './skills/Skills'
export { default as Work } from './work/Work'
export { default as Home } from './home/Home'
export { default as Contact } from './contact/Contact'
